/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package com.jaegerinitiative.sherryview;

import com.jaegerinitiative.fakedata.GenerateJaegerList;
import com.jaegerinitiative.data.Jaeger;
import com.jaegerinitiative.fakedata.GenerateJobsList;
import com.jaegerinitiative.sherryview.SVEmpTableModel.ColumnListEmp;
import java.awt.Component;
import java.awt.event.ActionListener;
import javafx.event.ActionEvent;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.jaegerinitiative.sherryview//SVEditorTopComponent//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "SVEditorTopComponentTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "properties", openAtStartup = true)
@ActionID(category = "Window", id = "com.jaegerinitiative.sherryview.SVEditorTopComponentTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_SVEditorTopComponentAction",
        preferredID = "SVEditorTopComponentTopComponent"
)
@Messages({
    "CTL_SVEditorTopComponentAction=SVEditorTopComponent",
    "CTL_SVEditorTopComponentTopComponent=SVEditorTopComponent Window",
    "HINT_SVEditorTopComponentTopComponent=This is a SVEditorTopComponent window"
})
public final class SVEmpTopComponent extends TopComponent {
    private SVEditorTopComponent _svEditor;
    public SVEmpTopComponent() {
        initComponents();
        fillComponents();
        setName(Bundle.CTL_SVEditorTopComponentTopComponent());
        setToolTipText(Bundle.HINT_SVEditorTopComponentTopComponent());
        _svEditor = new SVEditorTopComponent();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        _empTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        _taskItemTable = new javax.swing.JTable();

        _empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Adam Korynta", "25", null},
                {"Chris Bradley", "75", null},
                {"Deziree Dizon", "90", null},
                {"Joshua DeGeorge", "2", null},
                {"Ryan Miles", "60", null}
            },
            new String [] {
                "Employee", "Monthly %", "Poke"
            }
        ));
        _empTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(_empTable);
        if (_empTable.getColumnModel().getColumnCount() > 0) {
            _empTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(SVEmpTopComponent.class, "SVEmpTopComponent._empTable.columnModel.title0")); // NOI18N
            _empTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(SVEmpTopComponent.class, "SVEmpTopComponent._empTable.columnModel.title1")); // NOI18N
            _empTable.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(SVEmpTopComponent.class, "SVEmpTopComponent._empTable.columnModel.title2")); // NOI18N
        }

        _taskItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CWMS Maintenance", "200", "250"},
                {"REGI Maintenance", "400", "700"},
                {"ResSim", "0", "1000"},
                {"Rating Editor", "900", null}
            },
            new String [] {
                "Job", "Used", "Allocated"
            }
        ));
        jScrollPane2.setViewportView(_taskItemTable);
        if (_taskItemTable.getColumnModel().getColumnCount() > 0) {
            _taskItemTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(SVEmpTopComponent.class, "SVEmpTopComponent._taskItemTable.columnModel.title0")); // NOI18N
            _taskItemTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(SVEmpTopComponent.class, "SVEmpTopComponent._taskItemTable.columnModel.title1")); // NOI18N
            _taskItemTable.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(SVEmpTopComponent.class, "SVEmpTopComponent._taskItemTable.columnModel.title2")); // NOI18N
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable _empTable;
    private javax.swing.JTable _taskItemTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        _svEditor.open();
    }
    
    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }
    
    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }
    private void fillComponents() {
        
        _empTable= new SVEmpTable();
        _empTable.setModel(new SVEmpTableModel(GenerateJaegerList.getInstance()));
        
        _taskItemTable.setModel(new SVJobTableModel(GenerateJobsList.getInstance()));
    }
    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    
    
}
