/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jaegerinitiative.login;

/**
 *
 * @author adam
 */
public class LoginFrame extends javax.swing.JPanel {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _usernameLabel = new javax.swing.JLabel();
        _passwordLabel = new javax.swing.JLabel();
        _usernameField = new javax.swing.JTextField();
        _passwordField = new javax.swing.JPasswordField();

        org.openide.awt.Mnemonics.setLocalizedText(_usernameLabel, org.openide.util.NbBundle.getMessage(LoginFrame.class, "LoginFrame._usernameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(_passwordLabel, org.openide.util.NbBundle.getMessage(LoginFrame.class, "LoginFrame._passwordLabel.text")); // NOI18N

        _usernameField.setText(org.openide.util.NbBundle.getMessage(LoginFrame.class, "LoginFrame._usernameField.text")); // NOI18N

        _passwordField.setText(org.openide.util.NbBundle.getMessage(LoginFrame.class, "LoginFrame._passwordField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_usernameLabel)
                    .addComponent(_passwordLabel))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_usernameField)
                    .addComponent(_passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_usernameLabel)
                    .addComponent(_usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_passwordLabel)
                    .addComponent(_passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField _passwordField;
    private javax.swing.JLabel _passwordLabel;
    private javax.swing.JTextField _usernameField;
    private javax.swing.JLabel _usernameLabel;
    // End of variables declaration//GEN-END:variables
    
    public String getUsername(){
        return this._usernameField.getText();
    }
    
    public char[] getPassword(){
        return this._passwordField.getPassword();
    }
}
